name       : gnome-calculator
version    : 3.22.2
release    : 12
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-calculator/3.22/gnome-calculator-3.22.2.tar.xz : 99a7f42d632dc97a78f0962798983161d1ef4da08b866ee45fdd644f683f340e
license    : GPL-2.0+
component  : desktop.gnome
summary    : Gnome Calculator Application
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(libsoup-2.4)
    - itstool
description: |
    A tool for calculating mathematical equations. Uses standard mathematical notation where possible (so users do not have to learn the application when they already know maths). Easy enough to use for simple maths (add, subtract, multiply, divide). Powerful enough for mid-level mathematics (though not at the expense of being easy for simple mathematics).
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
