name        : gnome-calculator
version     : 3.18.3
release     : 10
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-calculator/3.18/gnome-calculator-3.18.3.tar.xz : c376a4a14a3f7946b799b8458ac4cf2694735fc7c20e90cfda29e209439e32ff
license     : GPL-2.0+
summary     : Gnome Calculator Application
builddeps   :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtksourceview-3.0)
    - itstool
description : |
    A tool for calculating mathematical equations. Uses standard mathematical notation where possible (so users do not have to learn the application when they already know maths). Easy enough to use for simple maths (add, subtract, multiply, divide). Powerful enough for mid-level mathematics (though not at the expense of being easy for simple mathematics).
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
