name       : gnome-calculator
version    : 3.22.3
release    : 13
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-calculator/3.22/gnome-calculator-3.22.3.tar.xz : 8dba14b449a6a141aaf86b2ce8d8722bd03b3c398892ba583127d2a2995e52ca
license    : GPL-2.0+
component  : desktop.gnome
summary    : Gnome Calculator Application
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(libsoup-2.4)
    - itstool
description: |
    A tool for calculating mathematical equations. Uses standard mathematical notation where possible (so users do not have to learn the application when they already know maths). Easy enough to use for simple maths (add, subtract, multiply, divide). Powerful enough for mid-level mathematics (though not at the expense of being easy for simple mathematics).
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
