name       : gnome-calculator
version    : 3.38.1
release    : 26
source     :
    - https://download.gnome.org/sources/gnome-calculator/3.38/gnome-calculator-3.38.1.tar.xz : 7cffffd07f7a463d65d30a3d67e1cf774a76cfe1f80194aae7168d21687b5249
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Gnome Calculator Application
description: |
    A tool for calculating mathematical equations. Uses standard mathematical notation where possible (so users do not have to learn the application when they already know maths). Easy enough to use for simple maths (add, subtract, multiply, divide). Powerful enough for mid-level mathematics (though not at the expense of being easy for simple mathematics).
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtksourceview-4)
    - pkgconfig(libsoup-2.4)
    - itstool
    - vala
rundeps    :
    - devel : libgtk-3-devel
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
